# Generated by Django 5.1.1 on 2024-10-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_prescription_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
